language: go
go:
- 1.6
sudo: false
script: make test
branches:
  except:
  - gh-pages
before_deploy:
- PATH="$HOME/gopath/bin:$PATH" make dist
deploy:
  provider: releases
  api_key:
    secure: aIw9Rt8yY8hQu+KFqgESP1v228sX709zTjWIA+mWW1NG5O6m99pjB8UDhar1SBtwZ8ovf/pYfvox4MFEzTsP3cJ9YKrK2HlodZZy46l7qaCpplhd+GIY7JOJlWgeUK5smgaVq60ITvTGoJtcLLX+TedkfaKfQsehIg6Sob4WhQ8=
  file:
  - dist/direnv.darwin-386
  - dist/direnv.darwin-amd64
  - dist/direnv.linux-386
  - dist/direnv.linux-amd64
  - dist/direnv.linux-arm
  - dist/direnv.freebsd-386
  - dist/direnv.freebsd-amd64
  - dist/direnv.openbsd-386
  - dist/direnv.openbsd-amd64
  - dist/direnv.windows-386.exe
  - dist/direnv.windows-amd64.exe
  - dist/direnv.freebsd-arm
  - dist/direnv.netbsd-386
  - dist/direnv.netbsd-amd64
  - dist/direnv.netbsd-arm
  skip_cleanup: true
  on:
    tags: true
