schema = 3

[mod]
  [mod."github.com/BurntSushi/toml"]
    version = "v1.3.2"
    hash = "sha256-FIwyH67KryRWI9Bk4R8s1zFP0IgKR4L66wNQJYQZLeg="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.19"
    hash = "sha256-wYQqGxeqV3Elkmn26Md8mKZ/viw598R4Ych3vtt72YE="
  [mod."golang.org/x/mod"]
    version = "v0.12.0"
    hash = "sha256-M/oXnzm7odpJdQzEnG6W0pNYtl0uhOM/l7qgfGVpU2M="
  [mod."golang.org/x/sys"]
    version = "v0.6.0"
    hash = "sha256-zAgxiTuL24sGhbXrna9R1UYqLQh46ldztpumOScmduY="
